Dev mac
GAIGResearch/Stratega pull request #10
Opened 2020-12-10 12:29 UTC by GAIGResearch

Compatibility with Mac

2020-12-10 18:24 UTC, CommanderCero requested changes

2020-12-10 18:24 UTC, CommanderCero commented on GUI/include/MapLayer.h
> +				sf::Texture& texture = RenderLayer<GameState>::assetCache.getTexture("tile_" + std::to_string(targetTile.tileTypeID));
why is adding RenderLayer<GameState>:: necessary?
I mean we only inherit from one class

2020-12-10 18:27 UTC, CommanderCero requested changes

2020-12-10 18:27 UTC, CommanderCero commented on Stratega/include/Representation/BuildContext.h
> +	typedef __int64_t TimeVal;
shouldnt it be int64_t instead of __int64_t

2020-12-11 07:45 UTC, GAIGResearch commented on GUI/include/MapLayer.h
> +				sf::Texture& texture = RenderLayer<GameState>::assetCache.getTexture("tile_" + std::to_string(targetTile.tileTypeID));
Done.

2020-12-11 07:50 UTC, GAIGResearch commented on Stratega/include/Representation/BuildContext.h
> +	typedef __int64_t TimeVal;
Changed to int64_t

2020-12-11 08:00 UTC, merged